### ISSUE TITLE
Credentials Encryption

### ISSUE THREAD

**Issue by GuyLewin** [eshaham/israeli-ynab-updater#37] opened 2019-01-26 12:38 UTC
Regarding the following code:
https://github.com/eshaham/israeli-ynab-updater/blob/5b0399ca3c3d2842a2e392a0eb14939c551e8438/src/helpers/crypto.js#L3-L10

Even if the credentials are encrypted with AES with a preconfigured key, it's still decryptable by simply the file (since the key is on GitHub).

How about moving to using system's keychain management instead? With a cross-platform library such as [keytar](https://www.npmjs.com/package/keytar)

**Comment by GuyLewin** [comment] 2019-01-26 17:47
You can look at [my code for configuring the accounts](https://github.com/GuyLewin/israel-finance-telegram-bot/blob/master/src/setup.js) that is based on this project's setup.

**Comment by eshaham** [comment] 2019-01-27 12:35
Agreed, duplicate of #34 
Since this tool is being used locally on the user's workstation, it's not critical in my opinion.
Yet again, we need to fix it - PR is welcome!

**Closed by eshaham** 2019-01-27 12:35 UTC
Labels: duplicate, enhancement
